## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
unique_counts = application_df.nunique()
print(unique_counts)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
columns_to_check = ['APPLICATION_TYPE']

In [5]:
# Look at APPLICATION_TYPE value counts for binning
for column in columns_to_check:
  if application_df[column].nunique() > 10:
    print(f"\nColumn: {'APPLICATION_TYPE'}")
    print(application_df[column].value_counts())

Column: APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 200

application_type_counts = application_df['APPLICATION_TYPE'].value_counts()

application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()



# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(application_types_to_replace,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
print("CLASSIFICATION value counts")
print(classification_counts)

CLASSIFICATION value counts
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts_1 = classification_counts[classification_counts > 1]
print("CLASSIFICATION value counts > 1")
print(classification_counts_1)

CLASSIFICATION value counts > 1
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classification_cutoff_value = 1000

classification_counts = application_df["CLASSIFICATION"].value_counts()

classifications_to_replace = classification_counts[classification_counts < classification_cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [17]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_encoded = pd.get_dummies(application_df, columns=['APPLICATION_TYPE', 'CLASSIFICATION'])
print(application_df_encoded.head())

        AFFILIATION      USE_CASE  ORGANIZATION  STATUS     INCOME_AMT  \
0       Independent    ProductDev   Association       1              0
1       Independent  Preservation  Co-operative       1         1-9999
2  CompanySponsored    ProductDev   Association       1              0
3  CompanySponsored  Preservation         Trust       1    10000-24999
4       Independent     Heathcare         Trust       1  100000-499999

  SPECIAL_CONSIDERATIONS  ASK_AMT  IS_SUCCESSFUL  APPLICATION_TYPE_Other  \
0                      N     5000              1                       0
1                      N   108590              1                       0
2                      N     5000              0                       0
3                      N     6692              1                       0
4                      N   142590              1                       0

   APPLICATION_TYPE_T10  ...  APPLICATION_TYPE_T5  APPLICATION_TYPE_T6  \
0                     1  ...                    0                    0
1                     0  ...                    0                    0
2                     0  ...                    1                    0
3                     0  ...                    0                    0
4                     0  ...                    0                    0

   APPLICATION_TYPE_T7  APPLICATION_TYPE_T8  CLASSIFICATION_C1000  \
0                    0                    0                     1
1                    0                    0                     0
2                    0                    0                     0
3                    0                    0                     0
4                    0                    0                     1

   CLASSIFICATION_C1200  CLASSIFICATION_C2000  CLASSIFICATION_C2100  \
0                     0                     0                     0
1                     0                     1                     0
2                     0                     0                     0
3                     0                     1                     0
4                     0                     0                     0

   CLASSIFICATION_C3000  CLASSIFICATION_Other
0                     0                     0
1                     0                     0
2                     1                     0
3                     0                     0
4                     0                     0

[5 rows x 23 columns]

In [25]:
print(application_df_encoded['INCOME_AMT'].value_counts())

application_df_encoded['INCOME_AMT'] = pd.to_numeric(application_df_encoded['INCOME_AMT'], errors='coerce')

print(application_df_encoded.dtypes)

0.0    24388
Name: INCOME_AMT, dtype: int64
AFFILIATION                object
USE_CASE                   object
ORGANIZATION               object
STATUS                      int64
INCOME_AMT                float64
SPECIAL_CONSIDERATIONS     object
ASK_AMT                     int64
IS_SUCCESSFUL               int64
APPLICATION_TYPE_Other      uint8
APPLICATION_TYPE_T10        uint8
APPLICATION_TYPE_T19        uint8
APPLICATION_TYPE_T3         uint8
APPLICATION_TYPE_T4         uint8
APPLICATION_TYPE_T5         uint8
APPLICATION_TYPE_T6         uint8
APPLICATION_TYPE_T7         uint8
APPLICATION_TYPE_T8         uint8
CLASSIFICATION_C1000        uint8
CLASSIFICATION_C1200        uint8
CLASSIFICATION_C2000        uint8
CLASSIFICATION_C2100        uint8
CLASSIFICATION_C3000        uint8
CLASSIFICATION_Other        uint8
dtype: object

In [26]:
# Split our preprocessed data into our features and target arrays
X = application_df_encoded.drop('IS_SUCCESSFUL', axis=1)
y = application_df_encoded['IS_SUCCESSFUL']
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (27439, 22)
X_test shape: (6860, 22)
y_train shape: (27439,)
y_test shape: (6860,)

In [27]:
X_train_encoded = pd.get_dummies(X_train, columns=['AFFILIATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS'])

In [29]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train_encoded)

# Scale the data
X_train_scaled = X_scaler.transform(X_train_encoded)
X_test_encoded = X_test_encoded.reindex(columns=X_train_encoded.columns, fill_value=0)
X_test_scaled = X_scaler.transform(X_test_encoded)

## Compile, Train and Evaluate the Model

In [36]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, input_dim=X_train_scaled.shape[1], activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 80)                2880

 dense_7 (Dense)             (None, 30)                2430

 dense_8 (Dense)             (None, 1)                 31

=================================================================
Total params: 5341 (20.86 KB)
Trainable params: 5341 (20.86 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [37]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# Compile the model
#  YOUR CODE GOES HERE

WARNING:tensorflow:From Z:\Travis\anaconda3\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

In [40]:
nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5430 - accuracy: 0.7350
Epoch 2/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7347
Epoch 3/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5433 - accuracy: 0.7337
Epoch 4/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5429 - accuracy: 0.7351
Epoch 5/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5430 - accuracy: 0.7344
Epoch 6/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7345
Epoch 7/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7344
Epoch 8/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7352
Epoch 9/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5426 - accuracy: 0.7357
Epoch 10/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7345
Epoch 11/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7366
Epoch 12/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5424 - accuracy: 0.7348
Epoch 13/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5423 - accuracy: 0.7349
Epoch 14/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7344
Epoch 15/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7349
Epoch 16/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7357
Epoch 17/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7349
Epoch 18/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7349
Epoch 19/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7357
Epoch 20/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5416 - accuracy: 0.7352
Epoch 21/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7365
Epoch 22/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7356
Epoch 23/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7353
Epoch 24/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7361
Epoch 25/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7357
Epoch 26/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7357
Epoch 27/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7358
Epoch 28/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5412 - accuracy: 0.7360
Epoch 29/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7363
Epoch 30/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7354
Epoch 31/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7357
Epoch 32/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7354
Epoch 33/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7367
Epoch 34/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7364
Epoch 35/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7360
Epoch 36/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5413 - accuracy: 0.7360
Epoch 37/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7359
Epoch 38/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7357
Epoch 39/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7359
Epoch 40/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7363
Epoch 41/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7359
Epoch 42/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7364
Epoch 43/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7353
Epoch 44/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5406 - accuracy: 0.7357
Epoch 45/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7368
Epoch 46/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7357
Epoch 47/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7355
Epoch 48/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7369
Epoch 49/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5404 - accuracy: 0.7368
Epoch 50/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7365
Epoch 51/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5406 - accuracy: 0.7365
Epoch 52/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7372
Epoch 53/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7358
Epoch 54/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7364
Epoch 55/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7366
Epoch 56/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7362
Epoch 57/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7361
Epoch 58/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7363
Epoch 59/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7367
Epoch 60/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5404 - accuracy: 0.7365
Epoch 61/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7364
Epoch 62/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7368
Epoch 63/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7367
Epoch 64/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7367
Epoch 65/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7369
Epoch 66/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7370
Epoch 67/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7371
Epoch 68/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5401 - accuracy: 0.7375
Epoch 69/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7364
Epoch 70/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7371
Epoch 71/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7369
Epoch 72/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7366
Epoch 73/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7363
Epoch 74/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7374
Epoch 75/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7373
Epoch 76/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5400 - accuracy: 0.7368
Epoch 77/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7369
Epoch 78/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7362
Epoch 79/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7370
Epoch 80/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7367
Epoch 81/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7364
Epoch 82/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7375
Epoch 83/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7372
Epoch 84/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5395 - accuracy: 0.7364
Epoch 85/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7371
Epoch 86/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7370
Epoch 87/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7370
Epoch 88/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7374
Epoch 89/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7367
Epoch 90/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7373
Epoch 91/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5394 - accuracy: 0.7368
Epoch 92/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5389 - accuracy: 0.7376
Epoch 93/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7366
Epoch 94/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7373
Epoch 95/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7371
Epoch 96/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7371
Epoch 97/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7364
Epoch 98/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7369
Epoch 99/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5395 - accuracy: 0.7370
Epoch 100/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5394 - accuracy: 0.7376

In [41]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - loss: 0.5621 - accuracy: 0.7252 - 287ms/epoch - 1ms/step
Loss: 0.5621123909950256, Accuracy: 0.725218653678894

In [43]:
# Export our model to HDF5 file
model_filepath = "Documents\AlphabetSoupCharity.h5"

nn.save(model_filepath)